# Generated by Django 6.1.1 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_subject_alter_classassignment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmarks",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentmarks",
            name="maximum_marks",
            field=models.IntegerField(default=100),
        ),
    ]
